// Catalogo ManualePro v1.0 — 94 procedure operative in 8 aree
export const AREE_PROCEDURE = {
  AMM: 'Amministrazione & Finanza',
  HR:  'Risorse Umane',
  COM: 'Commerciale — Gare, Offerte e Contratti',
  OPS: 'Operazioni — Cantieri e Produzione',
  IT:  'Information Technology',
  QUA: 'Qualità & Compliance — SGI',
  SIC: 'Sicurezza sul Lavoro — D.Lgs. 81/08',
  CS:  'Customer Service — Post-Consegna',
}

// La sigla CL (Contabilità Lavori) confluisce in ACQ, come da organigramma ufficiale
export const MAPPA_SIGLE = { CL: 'ACQ' }

export const CATALOGO_PROCEDURE = [
  { codice: 'PRO-AMM-001', area: 'AMM', titolo: 'Gestione del Ciclo Passivo — Acquisti su Commessa e Subappalti', funzioni: ['ACQ','AMM'] },
  { codice: 'PRO-AMM-002', area: 'AMM', titolo: 'Gestione del Ciclo Attivo — Fatturazione SAL e Incassi da Committente', funzioni: ['AMM'] },
  { codice: 'PRO-AMM-003', area: 'AMM', titolo: 'Gestione della Tesoreria e Liquidità di Commessa', funzioni: ['AMM'] },
  { codice: 'PRO-AMM-004', area: 'AMM', titolo: 'Chiusure Contabili Periodiche e Contabilità di Commessa', funzioni: ['AMM','CG'] },
  { codice: 'PRO-AMM-005', area: 'AMM', titolo: 'Redazione e Approvazione del Bilancio d\'Esercizio', funzioni: ['AMM','CG','DL'] },
  { codice: 'PRO-AMM-006', area: 'AMM', titolo: 'Gestione Budget e Controllo Costi di Commessa', funzioni: ['AMM','DTS'] },
  { codice: 'PRO-AMM-007', area: 'AMM', titolo: 'Adempimenti Fiscali e Dichiarativi (Edilizia)', funzioni: ['AMM','CG'] },
  { codice: 'PRO-AMM-008', area: 'AMM', titolo: 'Gestione Note Spese e Rimborsi — Personale di Cantiere', funzioni: ['AMM'] },
  { codice: 'PRO-AMM-009', area: 'AMM', titolo: 'Gestione Cassa di Cantiere e Fondi Spesa', funzioni: ['RC','AMM'] },
  { codice: 'PRO-AMM-010', area: 'AMM', titolo: 'Qualifica e Gestione Fornitori e Subappaltatori', funzioni: ['ACQ','RSGI'] },
  { codice: 'PRO-AMM-011', area: 'AMM', titolo: 'Gestione Cespiti, Mezzi d\'Opera e Attrezzature', funzioni: ['AMM','DTS'] },
  { codice: 'PRO-AMM-012', area: 'AMM', titolo: 'Gestione Investimenti e CAPEX — Mezzi e Impianti', funzioni: ['AMM','DTS','DL'] },
  { codice: 'PRO-HR-001', area: 'HR', titolo: 'Selezione e Assunzione — Personale di Cantiere e Tecnico', funzioni: ['HR'] },
  { codice: 'PRO-HR-002', area: 'HR', titolo: 'Onboarding Nuove Risorse — Piano 30-60-90 giorni', funzioni: ['HR'] },
  { codice: 'PRO-HR-003', area: 'HR', titolo: 'Gestione Presenze e Orari — Personale di Cantiere', funzioni: ['HR','RC'] },
  { codice: 'PRO-HR-004', area: 'HR', titolo: 'Formazione e Sviluppo Professionale', funzioni: ['HR','RSPP','DTS'] },
  { codice: 'PRO-HR-005', area: 'HR', titolo: 'Elaborazione Paghe — Edilizia e Cassa Edile', funzioni: ['HR','AMM'] },
  { codice: 'PRO-HR-006', area: 'HR', titolo: 'Gestione Malattia, Infortuni e Assenze Prolungate', funzioni: ['HR','RSPP'] },
  { codice: 'PRO-HR-007', area: 'HR', titolo: 'Valutazione delle Performance e MBO', funzioni: ['HR','DL'] },
  { codice: 'PRO-HR-008', area: 'HR', titolo: 'Gestione delle Cessazioni del Rapporto di Lavoro', funzioni: ['HR','AMM'] },
  { codice: 'PRO-HR-009', area: 'HR', titolo: 'Relazioni Sindacali — Edilizia e Cassa Edile', funzioni: ['HR','DL'] },
  { codice: 'PRO-HR-010', area: 'HR', titolo: 'Gestione Clima Aziendale e Welfare', funzioni: ['HR'] },
  { codice: 'PRO-HR-011', area: 'HR', titolo: 'Diversity, Equity & Inclusion', funzioni: ['HR','DL'] },
  { codice: 'PRO-HR-012', area: 'HR', titolo: 'Gestione Procedimenti Disciplinari', funzioni: ['HR','DL'] },
  { codice: 'PRO-HR-013', area: 'HR', titolo: 'Mobilità del Personale e Smart Working', funzioni: ['HR'] },
  { codice: 'PRO-COM-001', area: 'COM', titolo: 'Gestione e Qualificazione Opportunità Commerciali', funzioni: ['DC'] },
  { codice: 'PRO-COM-002', area: 'COM', titolo: 'Processo di Offerta e Preventivazione — Commesse Edili', funzioni: ['DTS','DC'] },
  { codice: 'PRO-COM-003', area: 'COM', titolo: 'Partecipazione a Gare d\'Appalto Pubbliche (D.Lgs. 36/2023)', funzioni: ['DC','AMM'] },
  { codice: 'PRO-COM-004', area: 'COM', titolo: 'Negoziazione e Stipula Contratti con il Committente', funzioni: ['DC','DL'] },
  { codice: 'PRO-COM-005', area: 'COM', titolo: 'Gestione Portafoglio Commesse e Rapporti con i Committenti', funzioni: ['DC','DTS'] },
  { codice: 'PRO-COM-006', area: 'COM', titolo: 'Gestione Varianti e Claim — Extra-Lavori e Riserve', funzioni: ['DTS','DL'] },
  { codice: 'PRO-COM-007', area: 'COM', titolo: 'Marketing e Comunicazione — Impresa di Costruzioni', funzioni: ['DC'] },
  { codice: 'PRO-COM-008', area: 'COM', titolo: 'Sviluppo e Posizionamento di Nuovi Servizi e Settori', funzioni: ['DC','DL'] },
  { codice: 'PRO-COM-009', area: 'COM', titolo: 'Analisi di Mercato — Appalti, Committenti e Concorrenza', funzioni: ['DC'] },
  { codice: 'PRO-COM-010', area: 'COM', titolo: 'Gestione Partner e Raggruppamenti Temporanei (ATI/RTI)', funzioni: ['DC','DL'] },
  { codice: 'PRO-COM-011', area: 'COM', titolo: 'Previsione delle Commesse e Budget Commerciale', funzioni: ['DC','AMM'] },
  { codice: 'PRO-OPS-001', area: 'OPS', titolo: 'Pianificazione della Commessa e Cronoprogramma Lavori', funzioni: ['DTS','RC'] },
  { codice: 'PRO-OPS-002', area: 'OPS', titolo: 'Approvvigionamento Materiali e Noli per Cantiere', funzioni: ['ACQ','DTS'] },
  { codice: 'PRO-OPS-003', area: 'OPS', titolo: 'Gestione Magazzino Materiali e Mezzi d\'Opera', funzioni: ['ACQ','RC'] },
  { codice: 'PRO-OPS-004', area: 'OPS', titolo: 'Gestione Subappaltatori Operativi in Cantiere', funzioni: ['RC','DTS'] },
  { codice: 'PRO-OPS-005', area: 'OPS', titolo: 'Controllo Avanzamento Lavori (CAL) e SAL di Cantiere', funzioni: ['DTS','RC','CL'] },
  { codice: 'PRO-OPS-006', area: 'OPS', titolo: 'Manutenzione Preventiva e Correttiva dei Mezzi d\'Opera', funzioni: ['DTS','RC'] },
  { codice: 'PRO-OPS-007', area: 'OPS', titolo: 'Logistica di Cantiere — Approvvigionamento e Movimentazione', funzioni: ['ACQ','RC'] },
  { codice: 'PRO-OPS-008', area: 'OPS', titolo: 'Gestione Non Conformità in Cantiere e Rilavorazioni', funzioni: ['RC','RSGI'] },
  { codice: 'PRO-OPS-009', area: 'OPS', titolo: 'Gestione della Capacità Produttiva e Risorse di Cantiere', funzioni: ['DTS'] },
  { codice: 'PRO-OPS-010', area: 'OPS', titolo: 'Controllo Costi di Commessa e Analisi degli Scostamenti', funzioni: ['AMM','DTS'] },
  { codice: 'PRO-OPS-011', area: 'OPS', titolo: 'Gestione Utilities e Consumi Energetici di Cantiere', funzioni: ['RC','DTS'] },
  { codice: 'PRO-OPS-012', area: 'OPS', titolo: 'Gestione Ambientale, Rifiuti di Cantiere e Sostenibilità', funzioni: ['RSPP','DTS'] },
  { codice: 'PRO-IT-001', area: 'IT', titolo: 'Gestione Accessi e Identità Digitali (IAM)', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-002', area: 'IT', titolo: 'Supporto Utenti e Gestione Richieste IT', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-003', area: 'IT', titolo: 'Gestione Incidenti Informatici', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-004', area: 'IT', titolo: 'Gestione Cambiamenti IT (Change Management)', funzioni: ['IT','DL'] },
  { codice: 'PRO-IT-005', area: 'IT', titolo: 'Backup, Ripristino Dati e Continuità Operativa', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-006', area: 'IT', titolo: 'Sicurezza Informatica e Cybersecurity', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-007', area: 'IT', titolo: 'Business Continuity e Disaster Recovery', funzioni: ['IT','DL'] },
  { codice: 'PRO-IT-008', area: 'IT', titolo: 'Inventario Hardware, Software e Licenze', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-009', area: 'IT', titolo: 'Gestione Progetti IT e Digitalizzazione Cantiere', funzioni: ['IT','DTS'] },
  { codice: 'PRO-IT-010', area: 'IT', titolo: 'Gestione Fornitori IT e Contratti SLA', funzioni: ['IT','AMM'] },
  { codice: 'PRO-IT-011', area: 'IT', titolo: 'Conformità GDPR e Protezione Dati', funzioni: ['IT','RSGI'] },
  { codice: 'PRO-IT-012', area: 'IT', titolo: 'Gestione Rete, Infrastrutture e Connettività di Cantiere', funzioni: ['IT','RC'] },
  { codice: 'PRO-QUA-001', area: 'QUA', titolo: 'Gestione del Sistema di Gestione Integrato (SGI)', funzioni: ['RSGI','DL'] },
  { codice: 'PRO-QUA-002', area: 'QUA', titolo: 'Audit Interni — Qualità, Sicurezza e Cantieri', funzioni: ['RSGI'] },
  { codice: 'PRO-QUA-003', area: 'QUA', titolo: 'Gestione Non Conformità in Cantiere e in Sede', funzioni: ['RSGI'] },
  { codice: 'PRO-QUA-004', area: 'QUA', titolo: 'Azioni Correttive e Preventive (CAPA)', funzioni: ['RSGI'] },
  { codice: 'PRO-QUA-005', area: 'QUA', titolo: 'Controllo Qualità delle Lavorazioni in Cantiere', funzioni: ['DTS','RSGI'] },
  { codice: 'PRO-QUA-006', area: 'QUA', titolo: 'Gestione Certificazioni — ISO, SOA, CE, Qualificazioni', funzioni: ['RSGI','AMM'] },
  { codice: 'PRO-QUA-007', area: 'QUA', titolo: 'Qualifica e Valutazione Fornitori e Subappaltatori', funzioni: ['RSGI','ACQ'] },
  { codice: 'PRO-QUA-008', area: 'QUA', titolo: 'Gestione Reclami e Contestazioni del Committente', funzioni: ['DC','RSGI'] },
  { codice: 'PRO-QUA-009', area: 'QUA', titolo: 'Controllo Qualità Materiali in Accettazione (Incoming)', funzioni: ['RC','RSGI'] },
  { codice: 'PRO-QUA-010', area: 'QUA', titolo: 'Collaudi e Controllo Qualità Opere Eseguite', funzioni: ['DTS','RC'] },
  { codice: 'PRO-QUA-011', area: 'QUA', titolo: 'Taratura Strumenti di Misura e Controllo', funzioni: ['RSGI','RC'] },
  { codice: 'PRO-QUA-012', area: 'QUA', titolo: 'Compliance Normativa Settore Edile e Aggiornamenti', funzioni: ['RSGI','DL'] },
  { codice: 'PRO-SIC-001', area: 'SIC', titolo: 'Valutazione Rischi, DVR e POS di Cantiere', funzioni: ['RSPP','DL'] },
  { codice: 'PRO-SIC-002', area: 'SIC', titolo: 'Gestione DPI — Dispositivi di Protezione Individuale', funzioni: ['RSPP','RC'] },
  { codice: 'PRO-SIC-003', area: 'SIC', titolo: 'Formazione Obbligatoria Sicurezza in Edilizia', funzioni: ['RSPP','HR'] },
  { codice: 'PRO-SIC-004', area: 'SIC', titolo: 'Gestione Emergenze ed Evacuazione in Cantiere', funzioni: ['RSPP','RC'] },
  { codice: 'PRO-SIC-005', area: 'SIC', titolo: 'Gestione Infortuni e Quasi-Infortuni in Cantiere', funzioni: ['RSPP','HR'] },
  { codice: 'PRO-SIC-006', area: 'SIC', titolo: 'Sorveglianza Sanitaria — Lavoratori Edili', funzioni: ['RSPP','MC'] },
  { codice: 'PRO-SIC-007', area: 'SIC', titolo: 'Coordinamento Subappaltatori e Imprese Esterne (DUVRI)', funzioni: ['RSPP','RC'] },
  { codice: 'PRO-SIC-008', area: 'SIC', titolo: 'Sicurezza Lavorazioni a Rischio — Quota, Scavi, Demolizioni', funzioni: ['RSPP','DTS'] },
  { codice: 'PRO-SIC-009', area: 'SIC', titolo: 'Gestione Sostanze Pericolose e SDS in Cantiere', funzioni: ['RSPP','RC'] },
  { codice: 'PRO-SIC-010', area: 'SIC', titolo: 'Manutenzione e Verifica Attrezzature di Cantiere', funzioni: ['RSPP','DTS'] },
  { codice: 'PRO-SIC-011', area: 'SIC', titolo: 'Gestione Stress Lavoro-Correlato e Benessere in Cantiere', funzioni: ['RSPP','HR'] },
  { codice: 'PRO-CS-001', area: 'CS', titolo: 'Gestione Richieste e Assistenza Post-Consegna', funzioni: ['DC'] },
  { codice: 'PRO-CS-002', area: 'CS', titolo: 'Gestione Reclami Formali del Committente', funzioni: ['DC','RSGI'] },
  { codice: 'PRO-CS-003', area: 'CS', titolo: 'Gestione Difetti, Vizi e Garanzie sull\'Opera', funzioni: ['DTS','DC'] },
  { codice: 'PRO-CS-004', area: 'CS', titolo: 'Gestione Interventi in Garanzia e Riparazioni', funzioni: ['DTS','RC'] },
  { codice: 'PRO-CS-005', area: 'CS', titolo: 'Rilevazione Soddisfazione Committente (CSAT/NPS)', funzioni: ['DC','RSGI'] },
  { codice: 'PRO-CS-006', area: 'CS', titolo: 'Gestione Escalation e Controversie con il Committente', funzioni: ['DL','DC'] },
  { codice: 'PRO-CS-007', area: 'CS', titolo: 'Contratti di Manutenzione e Servizio Post-Opera (SLA)', funzioni: ['DC','DTS'] },
  { codice: 'PRO-CS-008', area: 'CS', titolo: 'Onboarding Nuovo Committente e Avvio Commessa', funzioni: ['DC','DTS'] },
  { codice: 'PRO-CS-009', area: 'CS', titolo: 'Gestione Fidelizzazione e Retention Committente', funzioni: ['DC'] },
  { codice: 'PRO-CS-010', area: 'CS', titolo: 'Formazione Team su Relazioni con il Committente', funzioni: ['HR','DC'] },
  { codice: 'PRO-CS-011', area: 'CS', titolo: 'Reportistica e KPI del Servizio Post-Consegna', funzioni: ['DC','RSGI'] },
]
